version: '3'
services:
  go-htmx-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-htmx-server
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    # command: go run start
    tty: true